# NOTE: git depth=1 while cloning in Travis-CI provides incorrect .Lastmod dates for content pages.
enableGitInfo: true

# Enable GA in production.
Languages:
  en:
    params:
      GoogleAnalytics: UA-79782596-1
  ru:
    params:
      GoogleAnalytics: UA-79782596-2
