@ECHO OFF
REM Builds css files by sassc and whole static html site by hugo.
REM
REM Created by Alexander Borsuk <me@alex.bio> from Minsk, Belarus.

SETLOCAL

REM hugo publish folder where static html content is generated.
SET out_dir=docs

REM Is git present in PATH?
WHERE /Q git || ECHO ERROR Please install git for Windows or GitHub Desktop. && EXIT /B 1

REM Is it a root folder?
IF NOT EXIST config.yaml (
  ECHO ERROR: Please launch this script from the site root folder.
  EXIT /B 1
)

REM Is it a git repo?
IF NOT EXIST .git (
  ECHO ERROR: This is not a git repository. It should be a GitHub cloned repo.
  EXIT /B 1
)

REM Repo should be up-to-date.
git remote update || ECHO ERROR with git remote update && EXIT /B 1

REM Setup cloned git repo in the generated folder.
IF NOT EXIST %out_dir%\.git (
  ECHO Initializing %out_dir% folder and binding it to gh-pages branch of the same repository.
  RMDIR /S /Q %out_dir%
  ROBOCOPY /E /NJH /NJS /NP /NS /NC /NFL /NDL .git %out_dir%\.git
  IF %ERRORLEVEL% GTR 7 (
    ECHO ERROR with robocopy
    EXIT /B 1
  )
)

REM Initialize and switch to gh-pages branch in the docs/.git repo.
PUSHD %out_dir% || ECHO ERROR with PUSHD %out_dir% && EXIT /B 1
git checkout gh-pages > nul 2>&1 || (
  git checkout --orphan gh-pages || ECHO ERROR with git checkout --orphan gh-pages && EXIT /B 1
  git rm -rf . || ECHO ERROR with git rm && EXIT /B 1
)
REM Clean all untracked files.
git clean -f
POPD

REM Build/generate static web site.
CALL %~dp0\build.cmd || ECHO ERROR while calling build.cmd && EXIT /B 1

REM Check if there are any changes to publish.
PUSHD %out_dir% || ECHO ERROR with PUSHD %out_dir% && EXIT /B 1
REM Trick with `find` counts output lines from previous command, like `wc -l` on *nix systems.
FOR /F "tokens=* USEBACKQ" %%F IN (`git status --porcelain ^| FIND /C /V ""`) DO SET changed_files=%%F
IF %changed_files% EQU 0 (
  ECHO There is nothing to publish. Have you made any changes?
  POPD
  EXIT /B 0
)

REM Publish web site to Github Pages.
git add -A || ECHO ERROR with git add -A && EXIT /B 1
git commit -m "Regenerated by deployment script." || ECHO ERROR with git commit -m && EXIT /B 1
git push -u origin gh-pages || ECHO ERROR with git push && EXIT /B 1
POPD
ECHO Successfully published changes to GitHub Pages.
