# ru and com are copypastes to avoid error:
# Run peaceiris/actions-gh-pages@v3
# [INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
# Dump inputs
# Setup auth token
#   [INFO] setup SSH deploy key
#   /usr/bin/chmod 700 /home/runner/.ssh
#   [INFO] wrote /home/runner/.ssh/known_hosts
#   /usr/bin/chmod 600 /home/runner/.ssh/known_hosts
#   [INFO] wrote /home/runner/.ssh/github
#   /usr/bin/chmod 600 /home/runner/.ssh/github
#   [INFO] wrote /home/runner/.ssh/config
#   /usr/bin/chmod 600 /home/runner/.ssh/config
#   unix_listener: cannot bind to path /tmp/ssh-auth.sock: Address already in use
#   Error: Action failed with "Command failed: ssh-agent -a /tmp/ssh-auth.sock
#   unix_listener: cannot bind to path /tmp/ssh-auth.sock: Address already in use

name: Deploy www.vibrobox.com
on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - .github/**
      - '!.github/workflows/deploy-com.yaml'  # Run check on self change
      - LICENSE
      - README.md

jobs:
  deploy:
    name: Deploy www.vibrobox.com
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.116.1'
          extended: true

      # Required for hugo's built-in postcss/autoprefixer
      - name: Install npm dependencies
        run: |
          npm i

      - name: Build
        run: hugo --environment production

      - name: Deploy to www.vibrobox.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_COM }}
          external_repository: VibroBox/www.vibrobox.com
          publish_dir: ./public/en
          user_name: Alexander Borsuk
          user_email: alex@vibrobox.com
          publish_branch: master
          cname: www.vibrobox.com
